meteor add accounts-base
meteor add accounts-password
meteor add accounts-ui
meteor add alanning:roles
meteor add aldeed:autoform
meteor add aldeed:autoform-bs-datepicker
meteor add aldeed:collection2
meteor add aldeed:simple-schema
meteor add cfs:gridfs
meteor add cfs:standard-packages
meteor add chart:chart
meteor add chhib:morris
meteor add d3
meteor add email
meteor add imap
meteor add insecure
meteor add meteor-platform
meteor add mizzao:bootstrap-3
meteor add mrt:moment
meteor add msavin:mongol
meteor add npm-bcrypt
meteor add pfafman:font-awesome-4
meteor add sacha:spin
meteor add styling
meteor add userman
meteor add vsivsi:job-collection
